# The URL the site will be built for
base_url = "https://aurigabriel.com/blog"

title = "Auri's Blog"
description = "Engineering notes, practical software development, and build logs."

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

taxonomies = [
    { name = "tags", feed = false },
    { name = "categories", feed = false }
]


[markdown]

[markdown.highlighting]
style = "inline"
theme = "github-dark"

[extra]
posts_section = "post"
